### PR TITLE
feat(fish): Replacing exa with new eza

### PR DESCRIPTION
**Pull request by harshv5094**
On my setup, exa was facing some issues. So I checked and found out the exa has shifted their setup to eza now. So I've changed my setup commands from exa to eza and everthing works fine as it is now

### CODE REVIEW

**Comment by craftzdog** [comment]
Thanks!

**Comment by harshv5094** [comment]
Actually, Your config was my first gateway to use neovim as my code editor. I'm really enjoying it, and I'm grateful that you've shared your neovim setup with us. Thank You!

**Comment by harshv5094** [comment]
hey @craftzdog! Does exa still runs on MacOS or it is also replaced by eza. If yes then may I change the fish shell config for mac os

**Comment by craftzdog** [comment]
yes, please!

**Pull request merged**
