### PR TITLE
Fixed determining OS for config

### PR DESCRIPTION
**Pull request by darktime78**

### CODE REVIEW

**Comment by craftzdog** [comment]
What does it solve?

**Comment by darktime78** [comment]
Hello, you're right, it doesn't solve anything. I wrote wrong name for commit. I checked on WSL 2 Debian.
image
The buffer works fine with the Linux config.
image
 This is more of a cosmetic config, I thought that it would be more correct to determine the OS this way. If you don't see the point in it, you can close the pull request.

**Comment by craftzdog** [comment]
ok but `craftzdog.wsl` is no longer loaded on WSL in your PR.

**Comment by darktime78** [comment]
Forgive me dear sir, I misled you. I figured out why it works. I installed 2 versions of neovim windows and WSL linux. This works in both versions because the windows version has the file .../Neovim/bin/win32yank.exe and has set the path to the folder ".../Neovim/bin" in PATH
And I found documentation neovim
https://github.com/neovim/neovim/wiki/FAQ#how-to-use-the-windows-clipboard-from-wsl
**"If Neovim is only installed within our WSL distribution, we can just install win32yank.exe manually"** 
This proves that the WSL config is no longer needed.

**Comment by craftzdog** [comment]
Got it. Can you also remove `wsl.lua` as it is no longer necessary?

**Comment by darktime78** [comment]
Yes, sure. Done.

**Pull request merged**
