### PR TITLE
A prototype of automation script for installing craftzdog's setup

### PR DESCRIPTION
**Pull request by harshv5094**
This is a prototype script for the autoinstallation of Craftzdog's setup. This script only works for macOS and Ubuntu Linux,
see #142 for more info. @craftzdog, can you test it and tell me if the script is working or not. I don't have a macOS system so I was unable to test the homebrew option.

Here are some screenshot
image

image

If there is some problem, or you want to add new suggestion just message me on #142

### CODE REVIEW

**Comment by harshv5094** [comment]
just run `install.sh` in the `.scripts` folder.

**Comment by harshv5094** [comment]
I've done the changes as suggested by @fisenkodv

**Comment by fisenkodv** [comment]
> I've done the changes as suggested by @fisenkodv

@harshv5094 thank you!

**Comment by harshv5094** [comment]
@craftzdog can you review my code. I think i've done some mistakes in fish script config. I can't seem to figure out what went wrong

**Comment by CofCat456** [comment]
@harshv5094 Have you installed Fisher?

**Comment by harshv5094** [comment]
Yeah, I just want to ask that should I copy fish folder from craftzdog setup or run the script only which creates link for the files directly in `.config/fish` directly

**Comment by CofCat456** [comment]
I personally prefer the linking method, as it relates to Git, making it easy to update with ‘git pull.’

By the way, I didn't see any downloading Fisher in the script. Please correct me if I'm wrong.

**Comment by harshv5094** [comment]
I've used the previous script provided by craftzdog. I was going to ask him about should I add the fisher installation in his script

**Comment by harshv5094** [comment]
@CofCat456 Do you think my script has no problem to merge with craftzdog setup

**Comment by CofCat456** [comment]
@harshv5094 I haven't run it yet, but it LGTM. I'm looking forward to the merge!

**Comment by craftzdog** [comment]
Can you use `fish_plugins` file?
https://github.com/jorgebucaran/fisher?tab=readme-ov-file#using-your-fish_plugins-file

**Comment by harshv5094** [comment]
I'll try it.

**Comment by harshv5094** [comment]
Hey @craftzdog I've tried to implement it through `fish_plugins` file but there are some problems, first of all before running the fish script we need to install fisher, because every fisher installation resets the fish_plugin file, So it will be a problem to write the fish_plugins files again, this file is basically for updating your preinstalled plugins after installation.

**Comment by harshv5094** [comment]
Hey, Giving an update on `fish_plugin` problem. I didn`t found any solution quite yet. I'll try to find solution for craftzdog suggestion

**Pull request closed without merging**
