### PR TITLE
packer bootstrap, autoinstall servers

### PR DESCRIPTION
**Pull request by maxmx03**
## Changes

- packer will be installed automatically
- mason will install servers automatically (everytime you add new server config in lspconfig.lua)
- plugins config moved to ftdetect: mason.lua need to load before lspconfig.lua

## Reason

These changes will help new users.

### CODE REVIEW

**Comment by MrShortcut** [comment]
hey were you able to enable format on save on all file extension types for each language type?

**Comment by MrShortcut** [comment]
@maxmx03  hey were you able to enable format on save on all file extension types for each language type?

**Comment by maxmx03** [comment]
> @maxmx03 hey were you able to enable format on save on all file extension types for each language type?

yes, the plugin Takuya use to format javascript files didnt work for me, i had to config null-ls to start working.

Captura de tela de 2022-08-27 23-48-01

**Comment by MrShortcut** [comment]
@maxmx03 Do you have them in a public repository? Mine are public but similar to Takuya's and they don't work for me either 
; ( Can you give me a hand?

**Comment by craftzdog** [comment]
Thanks for the PR, will look into it

**Comment by craftzdog** [comment]
Why are other plugins like colorizer moved to ftdetect?

**Comment by maxmx03** [comment]
> Why are other plugins like colorizer moved to ftdetect? just moving `mason.rc.lua` to `plugin/0_mason.rc.lua` solves the issue, no?

yes you can do that or you can move only mason.rc.lua to ftdetect folder, i moved everything just to keep your files organized.

**Review by abhigyanmadhukalya — APPROVED** [review]

**Review by abhigyanmadhukalya — APPROVED** [review]
The following changes work without any hiccups or problems

**Comment by gmmoose20** [comment]
mason 'auto_installation' not working for me.. It's not installing server configured in lspconfig.lua

**Pull request closed without merging**
