### PR TITLE
fix(nvim): add new mappings

### PR DESCRIPTION
**Pull request by yunag**
The default mappings were removed in the last changes

### CODE REVIEW

**Review by coder054 — COMMENTED** [review]
Great, I like to map Ctrl J, Ctr K to move up and down on list of suggestions

**Comment by craftzdog** [comment]
Which changes are you talking about?

**Comment by yunag** [comment]
https://github.com/hrsh7th/nvim-cmp/commit/93cf84f7deb2bdb640ffbb1d2f8d6d412a7aa558

**Comment by coder054** [comment]
Actually, I think the plugin have this keymap by default, no need to do anything

**Comment by yunag** [comment]
I don't know, but in both Windows and Linux the completion menu doesn't work properly.

**Pull request closed without merging**
